package com.boveda.quesefy.controller;

import com.boveda.quesefy.domain.CreateEventRequest;
import com.boveda.quesefy.domain.UpdateEventRequest;
import com.boveda.quesefy.domain.dto.CreateEventRequestDto;
import com.boveda.quesefy.domain.dto.EventDto;
import com.boveda.quesefy.domain.dto.UpdateEventRequestDto;
import com.boveda.quesefy.domain.entity.Event;
import com.boveda.quesefy.mapper.EventMapper;
import com.boveda.quesefy.service.EventService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping(path = "/api/v1/events")
public class EventController {
    private final EventService eventService;
    private final EventMapper eventMapper;

    public EventController(EventService eventService, EventMapper eventMapper) {
        this.eventService = eventService;
        this.eventMapper = eventMapper;
    }

    @Operation(
            summary = "Create a new event",
            description = "Creates a new event and returns " +
                    "it in the returns it with a default " +
                    "EventStatus.DUE and autogenerated ID"
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "201",
                    description = "Event created successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = EventDto.class))
            ),
            @ApiResponse(
                    responseCode = "400",
                    description = "Invalid request data"
            )
    })
    @PostMapping
    public ResponseEntity<EventDto> createEvent(@Valid @RequestBody CreateEventRequestDto createEventRequestDto) {
        CreateEventRequest createEventRequest = eventMapper.fromDto(createEventRequestDto);
        Event event = eventService.createEvent(createEventRequest);
        EventDto createdEventDto = eventMapper.toDto(event);

        return new ResponseEntity<>(createdEventDto, HttpStatus.CREATED);
    }


    @Operation(
            summary = "List events",
            description = "Lists all events that have been created"
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "List of events returned successfully (can be empty)",
                    content = @Content(
                            mediaType = "application/json",
                            array = @ArraySchema(
                                    schema = @Schema(implementation = EventDto.class)
                            )
                    )),
    })
    @GetMapping
    public ResponseEntity<List<EventDto>> listEvents() {

        List<Event> events = eventService.listEvents();
        List<EventDto> eventDtoList = events.stream()
                .map(eventMapper::toDto)
                .toList();

        return ResponseEntity.ok(eventDtoList);
    }

    @Operation(
            summary = "Get event by ID",
            description = "Returns the event with the given id"
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Event found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = EventDto.class)
                    )),
            @ApiResponse(
                    responseCode = "404",
                    description = "Event not found"
            )
    })
    @GetMapping("/{id}")
    public ResponseEntity<EventDto> getEventById(@PathVariable UUID id) {
        Event event = eventService.getEventById(id);
        EventDto eventDto = eventMapper.toDto(event);

        return ResponseEntity.ok(eventDto);
    }

    @Operation(
            summary = "Update event by",
            description = "Updates an existing event when ID is provided"
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Event updated",
                    content = @Content(
                        mediaType = "application/json",
                        schema = @Schema(implementation = EventDto.class)
                    )),
            @ApiResponse(
                    responseCode = "404",
                    description = "Event not found"
            ),
            @ApiResponse(
                    responseCode = "400",
                    description = "Invalid request data"
            )
    })
    @PutMapping("/{id}")
    public ResponseEntity<EventDto> updateEvent(
            @PathVariable UUID id,
            @Valid @RequestBody UpdateEventRequestDto updateEventRequestDto
    ) {
        UpdateEventRequest updateEventRequest = eventMapper.fromDto(updateEventRequestDto);
        Event event = eventService.updateEvent(id, updateEventRequest);
        EventDto updatedEventDto = eventMapper.toDto(event);

        return ResponseEntity.ok(updatedEventDto);
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteEvent(@PathVariable UUID id) {
        eventService.delete(id);

        return ResponseEntity.noContent().build();
    }

}
