spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quesefy
    username: quesefy
    password: quesefy
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true