spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quesefy
    username: quesefy
    password: quesefy

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true